### ISSUE TITLE
redundance check: structures_xyz folder 

### ISSUE THREAD

**Issue by theonov13** [kaitrepte/porE#6]
NOTA BENE: DO NOT DELETE FIRST AND THINK LATER!

Please, first check if all files are the same in all folders. 

- https://github.com/kaitrepte/porE/tree/master/porE/structures_xyz
- https://github.com/kaitrepte/porE/tree/master/porE/gui/structures_xyz
- https://github.com/kaitrepte/porE/tree/master/examples/structures_xyz

And then decide on a global folder, e.g., named structures, and adjust all other paths. 
The global structure folder can have sub-folders xyz and cif.

**Comment by kaitrepte** [comment]
I cleaned this up, added the subfolder structure and changed all path.
