### ISSUE TITLE
Youtube video 

### ISSUE THREAD

**Issue by theonov13** [kaitrepte/porE#9]
May we make a small video about porE 
- Installation 
- Usage 
- Applications 
- More Details can be found in the article 

What do you think?

**Comment by kaitrepte** [comment]
I like the idea a lot. Let's think about it!

**Comment by theonov13** [comment]
Started: see https://www.youtube.com/watch?v=yp4IgFnDf9E

We should somehow mention the youtube videos. 
Maybe at the global README.md?

**Comment by kaitrepte** [comment]
I added the first video as a link to the README file, under Additional Information.
